#!/usr/bin/env ruby

require './lib/mycsv/scanner'
require './lib/mycsv/parser'
require './lib/mycsv/code_generator'

tokens = MYCsv::Scanner.scan(STDIN.read)
# puts tokens.inspect
ast = MYCsv::Parser.new.parse(tokens)
puts ast.inspect
